// Package memory reads curated memory entries and generates their index.
//
// The index is generated rather than hand-maintained because a hand-maintained
// list of what is in a directory disagrees with the directory eventually, and a
// context document whose whole value is trustworthiness cannot afford that.
package memory

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// Source points at material that does not travel with the repository.
//
// The discipline that goes with it: a memory entry must never depend on its
// source being present in order to be correct. State the takeaway in the entry;
// the source is corroboration and a route to more detail.
type Source struct {
	Kind    string `yaml:"kind"`    // transcript | harness-memory | other
	Machine string `yaml:"machine"` // which computer holds it
	Harness string `yaml:"harness"` // for kind: harness-memory
	Ref     string `yaml:"ref"`     // agent_id, resolvable through the trace index
	Note    string `yaml:"note"`
}

type Frontmatter struct {
	Name        string   `yaml:"name"`
	Description string   `yaml:"description"`
	Sources     []Source `yaml:"sources"`
	Metadata    struct {
		Type string `yaml:"type"`
	} `yaml:"metadata"`

	Type string `yaml:"-"` // flattened from Metadata.Type for convenience
	Path string `yaml:"-"` // basename, for linking from the index
}

const delim = "---"

func Parse(path string) (Frontmatter, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return Frontmatter{}, err
	}
	text := strings.ReplaceAll(string(b), "\r\n", "\n")
	if !strings.HasPrefix(text, delim+"\n") {
		return Frontmatter{}, fmt.Errorf("%s: no frontmatter", filepath.Base(path))
	}
	rest := text[len(delim)+1:]
	// The FIRST closing delimiter, not the last: a body may hold a horizontal
	// rule or quote a second frontmatter block, and searching from the end would
	// swallow the body into the YAML.
	end := strings.Index(rest, "\n"+delim)
	if end < 0 {
		return Frontmatter{}, fmt.Errorf("%s: frontmatter is not closed", filepath.Base(path))
	}

	var fm Frontmatter
	if err := yaml.Unmarshal([]byte(rest[:end]), &fm); err != nil {
		return Frontmatter{}, fmt.Errorf("%s: %w", filepath.Base(path), err)
	}
	if fm.Name == "" || fm.Description == "" {
		return Frontmatter{}, fmt.Errorf("%s: name and description are both required", filepath.Base(path))
	}
	fm.Type = fm.Metadata.Type
	if fm.Type == "" {
		fm.Type = "uncategorized"
	}
	fm.Path = filepath.Base(path)
	return fm, nil
}

// List reads every entry in a memory directory.
//
// It fails on the first unparseable entry rather than skipping it: an entry
// that silently drops out of the index is invisible, and the index would then
// be confidently incomplete.
func List(dir string) ([]Frontmatter, error) {
	matches, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		return nil, err
	}
	sort.Strings(matches)

	var out []Frontmatter
	for _, p := range matches {
		if filepath.Base(p) == "INDEX.md" {
			continue
		}
		fm, err := Parse(p)
		if err != nil {
			return nil, err
		}
		out = append(out, fm)
	}
	return out, nil
}

// typeOrder fixes the section order so the output is stable regardless of what
// happens to be on disk.
var typeOrder = []string{"user", "project", "feedback", "reference", "uncategorized"}

func RenderIndex(entries []Frontmatter) []byte {
	byType := map[string][]Frontmatter{}
	for _, e := range entries {
		byType[e.Type] = append(byType[e.Type], e)
	}
	var extra []string
	for k := range byType {
		known := false
		for _, t := range typeOrder {
			if t == k {
				known = true
			}
		}
		if !known {
			extra = append(extra, k)
		}
	}
	sort.Strings(extra)

	var b bytes.Buffer
	b.WriteString("# Memory index\n\n")
	b.WriteString("GENERATED by `agents index`. Do not hand-edit — the pre-commit guard\n")
	b.WriteString("regenerates this file and blocks the commit if it differs.\n")

	for _, typ := range append(append([]string{}, typeOrder...), extra...) {
		group := byType[typ]
		if len(group) == 0 {
			continue
		}
		sort.Slice(group, func(i, j int) bool { return group[i].Name < group[j].Name })

		fmt.Fprintf(&b, "\n## %s\n\n", typ)
		for _, e := range group {
			fmt.Fprintf(&b, "- [%s](%s) — %s", e.Name, e.Path, e.Description)
			if n := len(e.Sources); n > 0 {
				// Surfaced here because it is the one thing about an entry
				// that a reader on a different machine needs to know before
				// trusting the detail behind it.
				fmt.Fprintf(&b, " _(sources: %d)_", n)
			}
			b.WriteString("\n")
		}
	}
	return b.Bytes()
}

func WriteIndex(dir string) error {
	entries, err := List(dir)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "INDEX.md"), RenderIndex(entries), 0o644)
}
