// Package harness isolates everything that differs between coding-agent
// runtimes: what a hook payload is called, which events exist, what the
// generated config looks like, and what each runtime can and cannot tell us.
//
// Harness identity is always passed in explicitly. It is never inferred from
// the environment: Codex publishes no identifying variables of its own, and a
// Codex hook launched from a Claude Code session inherits ~14 CLAUDE_CODE_* and
// ANTHROPIC_* variables. Detection has false positives available and no true
// positives.
package harness

import (
	"crypto/rand"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"syscall"
)

// Semantic event names. These are what the command line and the record use;
// each adapter maps them to its own vendor spelling for wiring.
const (
	SessionStart  = "session-start"
	SubagentStart = "subagent-start"
	SubagentStop  = "subagent-stop"
	Stop          = "stop"
)

// Payload is the entire subset of a hook payload this tool will decode.
//
// It is deliberately exhaustive: encoding/json discards keys with no
// destination field, so anything absent here -- last_assistant_message,
// tool_input, tool_response -- cannot reach any writer, whatever a future
// harness decides to send.

type Adapter interface {
	Name() string
	HarnessDir() string
	NeedsSkillsSymlink() bool

	// WireConfigPath is the generated config file for a repo.
	WireConfigPath(repoRoot string) string

	// Wire writes that config, merging into whatever is already there.
	Wire(repoRoot, binary string) error

	// StripHooks removes this tool's own entries from a harness config, in
	// place, and adds nothing. Adapters differ in where their entries live --
	// Claude Code and Codex nest them under "hooks", Antigravity under "agents"
	// -- so the shape of the removal is per-harness even though the reason is
	// the same for all three. It takes no event list on purpose: see
	// stripHooksJSON for why an event-driven strip is the defect, not the fix.
	StripHooks(settings map[string]any) error

	// TrustSteps are the manual steps left after wiring. No harness lets a
	// freshly wired repo's hooks fire unattended, and defeating that gate is an
	// explicit non-goal.
	TrustSteps(repoRoot string) []string
}

var registry = map[string]Adapter{}

func register(a Adapter) { registry[a.Name()] = a }

func Get(name string) (Adapter, bool) {
	a, ok := registry[strings.ToLower(strings.TrimSpace(name))]
	return a, ok
}

// All returns every adapter in a stable order.
func All() []Adapter {
	names := []string{"claude-code", "codex", "antigravity"}
	var out []Adapter
	for _, n := range names {
		if a, ok := registry[n]; ok {
			out = append(out, a)
		}
	}
	return out
}

// Decode reads one hook payload. It is the single place where hook JSON becomes
// Go values, which is what makes the redaction guarantee auditable.
// quotePOSIXWord quotes a word for a POSIX shell only when it has to, so the
// common path stays readable in a config a human reads.
func quotePOSIXWord(word string) string {
	if word != "" && strings.IndexFunc(word, func(r rune) bool {
		return !(r >= 'a' && r <= 'z') && !(r >= 'A' && r <= 'Z') && !(r >= '0' && r <= '9') && !strings.ContainsRune("_@%+=:,./-", r)
	}) == -1 {
		return word
	}
	return "'" + strings.ReplaceAll(word, "'", `'"'"'`) + "'"
}

// ParseHookCommand recognizes only commands generated by agents. It accepts
// the historical safe-unquoted spelling and the current POSIX-quoted spelling.
func ParseHookCommand(command string) (binary, harnessName, semantic string, ok bool) {
	words, ok := splitShellWords(command)
	if !ok || len(words) != 5 || words[1] != "hook" || words[3] != "--harness" {
		return "", "", "", false
	}
	binary, semantic, harnessName = words[0], words[2], words[4]
	if !filepath.IsAbs(binary) || !isOwnedBinary(binary) || !knownSemantic(semantic) || !knownHarness(harnessName) {
		return "", "", "", false
	}
	// Two spellings are recognised: the quoted one this tool writes, and the
	// unquoted argument order an earlier version wrote. The second is only
	// accepted when the binary needs no quoting: if it does, the two spellings
	// are the same string and accepting the unquoted form unconditionally would
	// widen what `wire` is allowed to delete from a config this tool does not
	// own.
	current := fmt.Sprintf("%s hook %s --harness %s", quotePOSIXWord(binary), semantic, harnessName)
	if command == current {
		return binary, harnessName, semantic, true
	}
	legacy := fmt.Sprintf("%s hook %s --harness %s", binary, semantic, harnessName)
	if command == legacy && quotePOSIXWord(binary) == binary {
		return binary, harnessName, semantic, true
	}
	return "", "", "", false
}

func IsOwnedHookCommand(command string) bool {
	_, _, _, ok := ParseHookCommand(command)
	return ok
}

// ResemblesHookCommand recognizes the *shape* agents generates without
// requiring the binary to be named `agents`. It is deliberately wider than
// ParseHookCommand, and the asymmetry is the point: stripOurs deletes entries
// from a config we do not own, so what we delete must stay narrow, while what
// we are willing to *report* can be broad.
//
// The gap between the two is not hypothetical. A test that wired this
// repository with the ephemeral `agents.test` binary left entries that
// ParseHookCommand refused -- correctly, by its own rule -- so wire never
// replaced them and doctor never counted them. They accumulated four per run
// and failed loudly at every session start while doctor reported the wiring
// exact. Nothing acts on this predicate except a diagnostic.
func ResemblesHookCommand(command string) bool {
	words, ok := splitShellWords(command)
	if !ok || len(words) != 5 || words[1] != "hook" || words[3] != "--harness" {
		return false
	}
	return filepath.IsAbs(words[0]) && knownSemantic(words[2]) && knownHarness(words[4])
}

func isOwnedBinary(binary string) bool {
	base := filepath.Base(binary)
	return base == "agents" || base == "agents-test-bin" || base == "agents-standalone"
}

func knownSemantic(semantic string) bool {
	switch semantic {
	case SessionStart, SubagentStart, SubagentStop, Stop:
		return true
	default:
		return false
	}
}

func knownHarness(name string) bool {
	switch name {
	case "claude-code", "codex", "antigravity":
		return true
	default:
		return false
	}
}

func splitShellWords(command string) ([]string, bool) {
	var words []string
	var word strings.Builder
	started := false
	quote := byte(0)
	for i := 0; i < len(command); i++ {
		c := command[i]
		if quote != 0 {
			if c == quote {
				quote = 0
				continue
			}
			if quote == '"' && c == '\\' {
				i++
				if i >= len(command) {
					return nil, false
				}
				word.WriteByte(command[i])
				continue
			}
			word.WriteByte(c)
			continue
		}
		switch c {
		case '\'', '"':
			quote = c
			started = true
		case '\\':
			i++
			if i >= len(command) {
				return nil, false
			}
			word.WriteByte(command[i])
			started = true
		case ' ', '\t', '\r', '\n':
			if started {
				words = append(words, word.String())
				word.Reset()
				started = false
			}
		default:
			word.WriteByte(c)
			started = true
		}
	}
	if quote != 0 {
		return nil, false
	}
	if started {
		words = append(words, word.String())
	}
	return words, true
}

type configSnapshot struct {
	exists bool
	info   os.FileInfo
	perm   os.FileMode
}

type skillsSnapshot struct {
	exists bool
	info   os.FileInfo
}

var beforeWirePublish = func() {}

// openHarnessDir opens one repository-controlled child below the repository
// root without allowing that child to redirect writes through a symlink. The
// returned Root remains bound to the checked directory if a pathname above it
// is renamed after this function returns.
func openHarnessDir(repoRoot, name string) (*os.Root, string, error) {
	root, err := os.OpenRoot(repoRoot)
	if err != nil {
		return nil, "", err
	}
	defer root.Close()

	path := filepath.Join(repoRoot, name)
	for {
		info, err := root.Lstat(name)
		if os.IsNotExist(err) {
			if err := root.Mkdir(name, 0o755); err != nil && !os.IsExist(err) {
				return nil, "", err
			}
			continue
		}
		if err != nil {
			return nil, "", err
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return nil, "", fmt.Errorf("%s is a symlink: refusing to wire outside the repository", path)
		}
		if !info.IsDir() {
			return nil, "", fmt.Errorf("%s is not a directory: move it aside before wiring", path)
		}

		child, err := root.OpenRoot(name)
		if err != nil {
			return nil, "", err
		}
		opened, err := child.Stat(".")
		if err != nil {
			child.Close()
			return nil, "", err
		}
		if !os.SameFile(info, opened) {
			child.Close()
			return nil, "", fmt.Errorf("%s changed while it was being opened: retry after ensuring it is a real directory", path)
		}
		return child, path, nil
	}
}

func isSingleLinkRegular(info os.FileInfo) bool {
	stat, ok := info.Sys().(*syscall.Stat_t)
	return info.Mode().IsRegular() && ok && stat.Nlink == 1
}

// acquireWireLock serializes this tool's writers without ever deleting a
// repository-controlled lock pathname. The small persistent inode is harmless;
// keeping it avoids a check-then-remove cleanup race that could delete a
// replacement object.
func acquireWireLock(dir *os.Root, dirPath string) (*os.File, error) {
	const name = ".agents-wire.lock"
	path := filepath.Join(dirPath, name)
	for {
		info, err := dir.Lstat(name)
		if os.IsNotExist(err) {
			file, err := dir.OpenFile(name, os.O_CREATE|os.O_EXCL|os.O_RDWR|syscall.O_CLOEXEC|syscall.O_NOFOLLOW|syscall.O_NONBLOCK, 0o600)
			if os.IsExist(err) {
				continue
			}
			if err != nil {
				return nil, err
			}
			opened, err := file.Stat()
			if err != nil || !isSingleLinkRegular(opened) {
				_ = file.Close()
				return nil, fmt.Errorf("%s is not a safe wire lock", path)
			}
			if err := syscall.Flock(int(file.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
				_ = file.Close()
				return nil, fmt.Errorf("another wire operation owns %s: %w", path, err)
			}
			return file, nil
		}
		if err != nil {
			return nil, err
		}
		if !isSingleLinkRegular(info) {
			return nil, fmt.Errorf("%s is not a single-link regular lock file", path)
		}
		file, err := dir.OpenFile(name, os.O_RDWR|syscall.O_CLOEXEC|syscall.O_NOFOLLOW|syscall.O_NONBLOCK, 0)
		if err != nil {
			return nil, err
		}
		opened, err := file.Stat()
		if err != nil || !isSingleLinkRegular(opened) || !os.SameFile(info, opened) {
			_ = file.Close()
			return nil, fmt.Errorf("%s changed while it was being opened", path)
		}
		if err := syscall.Flock(int(file.Fd()), syscall.LOCK_EX|syscall.LOCK_NB); err != nil {
			_ = file.Close()
			return nil, fmt.Errorf("another wire operation owns %s: %w", path, err)
		}
		return file, nil
	}
}

func releaseWireLock(file *os.File) {
	_ = syscall.Flock(int(file.Fd()), syscall.LOCK_UN)
	_ = file.Close()
}

// readHooksJSON reads only a verified, single-link regular config leaf. The
// nonblocking, no-follow open makes FIFOs and last-component symlinks errors
// instead of hangs or reads from another inode.
func readHooksJSON(dir *os.Root, dirPath, name string) (map[string]any, configSnapshot, error) {
	settings := map[string]any{}
	path := filepath.Join(dirPath, name)
	info, err := dir.Lstat(name)
	if os.IsNotExist(err) {
		return settings, configSnapshot{perm: 0o644}, nil
	}
	if err != nil {
		return nil, configSnapshot{}, err
	}
	if !isSingleLinkRegular(info) {
		return nil, configSnapshot{}, fmt.Errorf("%s is not a single-link regular file: refusing to read or replace it", path)
	}

	file, err := dir.OpenFile(name, os.O_RDONLY|syscall.O_CLOEXEC|syscall.O_NOFOLLOW|syscall.O_NONBLOCK, 0)
	if err != nil {
		return nil, configSnapshot{}, err
	}
	opened, err := file.Stat()
	if err != nil || !isSingleLinkRegular(opened) || !os.SameFile(info, opened) {
		_ = file.Close()
		return nil, configSnapshot{}, fmt.Errorf("%s changed while it was being opened: refusing to wire it", path)
	}
	b, readErr := io.ReadAll(file)
	closeErr := file.Close()
	if readErr != nil {
		return nil, configSnapshot{}, readErr
	}
	if closeErr != nil {
		return nil, configSnapshot{}, closeErr
	}
	if err := json.Unmarshal(b, &settings); err != nil {
		return nil, configSnapshot{}, fmt.Errorf("%s is not valid JSON; fix or remove it: %w", path, err)
	}
	return settings, configSnapshot{exists: true, info: opened, perm: opened.Mode().Perm()}, nil
}

// stripHooksJSON removes every entry this tool owns from a Claude Code or Codex
// config, and changes nothing else.
//
// It walks EVERY key under "hooks", not the events any harness currently
// declares. That distinction is the whole reason this function exists in this
// shape: a strip driven by an event list can only remove an entry for an event
// it recognises, so an entry left under any other key -- by an older version, a
// renamed event, or a hand edit -- survives every repair while remaining
// visible to `doctor`, which reports exactly that entry and tells the operator
// to run `wire`. An entry that no invocation can clear, with a remedy that
// provably does nothing, is worse than no check at all.
//
// It never adds. This tool no longer records harness lifecycle events, so there
// is no entry for it to want; what remains is the cleanup of entries an earlier
// version wrote. Foreign hooks and unknown shapes are preserved verbatim --
// silently dropping an audit hook would be serious misbehaviour, and that rule
// outlived the feature that motivated it.
func stripHooksJSON(settings map[string]any) ([]byte, error) {
	if settings == nil {
		return nil, fmt.Errorf("generated hook config root must be a JSON object, not null")
	}
	raw, present := settings["hooks"]
	if !present {
		return marshalSettings(settings)
	}
	hooks, ok := raw.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("generated hook config hooks must be a JSON object")
	}
	for event, rawGroups := range hooks {
		list, ok := rawGroups.([]any)
		if !ok {
			return nil, fmt.Errorf("generated hook config event %s must be a JSON array", event)
		}
		if kept := stripOurs(list); len(kept) == 0 {
			delete(hooks, event)
		} else {
			hooks[event] = kept
		}
	}
	if len(hooks) == 0 {
		delete(settings, "hooks")
	}
	return marshalSettings(settings)
}

func marshalSettings(settings map[string]any) ([]byte, error) {
	out, err := json.MarshalIndent(settings, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(out, '\n'), nil
}

// atomicWriteHooks publishes through the verified directory handle. The final
// rename replaces a racing leaf rather than following it; a pre-existing config
// must still be the exact verified inode and metadata observed while reading.
func atomicWriteHooks(dir *os.Root, dirPath, name string, data []byte, snapshot configSnapshot, validateSkills func() error) error {
	tmpName := ".agents-wire-tmp-" + rand.Text()
	file, err := dir.OpenFile(tmpName, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600)
	if err != nil {
		return err
	}
	defer func() {
		_ = file.Close()
		_ = dir.Remove(tmpName)
	}()
	if _, err := file.Write(data); err != nil {
		return err
	}
	if err := file.Chmod(snapshot.perm); err != nil {
		return err
	}
	if err := file.Sync(); err != nil {
		return err
	}
	if err := file.Close(); err != nil {
		return err
	}

	beforeWirePublish()
	current, err := dir.Lstat(name)
	if snapshot.exists {
		if err != nil || !isSingleLinkRegular(current) || !os.SameFile(snapshot.info, current) ||
			current.Mode() != snapshot.info.Mode() || current.Size() != snapshot.info.Size() ||
			!current.ModTime().Equal(snapshot.info.ModTime()) {
			return fmt.Errorf("%s changed while wiring: refusing to replace it", filepath.Join(dirPath, name))
		}
	} else if !os.IsNotExist(err) {
		if err != nil {
			return err
		}
		return fmt.Errorf("%s appeared while wiring: refusing to replace it", filepath.Join(dirPath, name))
	}
	if err := validateSkills(); err != nil {
		return err
	}
	if !snapshot.exists {
		// Link is an atomic create-if-absent publish. Rename would silently
		// overwrite a config that appeared after the absence check.
		return dir.Link(tmpName, name)
	}
	// A non-cooperating writer can still change an existing destination after
	// the final identity check. The per-harness lock closes that race between all
	// agents writers; portable os.Root has no compare-and-rename primitive for a
	// foreign process that ignores the lock.
	return dir.Rename(tmpName, name)
}

func preflightSkills(dir *os.Root, dirPath string) (skillsSnapshot, error) {
	const name = "skills"
	target := filepath.Join("..", ".agents", "skills")
	info, err := dir.Lstat(name)
	if os.IsNotExist(err) {
		return skillsSnapshot{}, nil
	}
	if err != nil {
		return skillsSnapshot{}, err
	}
	if info.Mode()&os.ModeSymlink == 0 {
		return skillsSnapshot{}, fmt.Errorf("%s exists and is not the managed skills symlink; move it aside before wiring", filepath.Join(dirPath, name))
	}
	got, err := dir.Readlink(name)
	if err != nil {
		return skillsSnapshot{}, err
	}
	if got != target {
		return skillsSnapshot{}, fmt.Errorf("%s points to %s, not the managed skills target; move it aside before wiring", filepath.Join(dirPath, name), got)
	}
	return skillsSnapshot{exists: true, info: info}, nil
}

func validateSkills(dir *os.Root, dirPath string, snapshot skillsSnapshot) error {
	const name = "skills"
	target := filepath.Join("..", ".agents", "skills")
	info, err := dir.Lstat(name)
	if err != nil || !snapshot.exists || info.Mode()&os.ModeSymlink == 0 || !os.SameFile(snapshot.info, info) {
		return fmt.Errorf("%s changed while wiring: refusing to publish hooks", filepath.Join(dirPath, name))
	}
	if got, err := dir.Readlink(name); err != nil || got != target {
		return fmt.Errorf("%s changed while wiring: refusing to publish hooks", filepath.Join(dirPath, name))
	}
	return nil
}

// wireRepository keeps every mutation below a verified harness directory and
// validates config and skills ownership before publishing either one.
func wireRepository(repoRoot string, a Adapter, binary string) error {
	harnessDir := a.HarnessDir()
	configName := filepath.Base(a.WireConfigPath(repoRoot))

	dir, dirPath, err := openHarnessDir(repoRoot, harnessDir)
	if err != nil {
		return err
	}
	defer dir.Close()
	lock, err := acquireWireLock(dir, dirPath)
	if err != nil {
		return err
	}
	defer releaseWireLock(lock)

	var skills skillsSnapshot
	if a.NeedsSkillsSymlink() {
		var err error
		skills, err = preflightSkills(dir, dirPath)
		if err != nil {
			return err
		}
	}

	settings, snapshot, err := readHooksJSON(dir, dirPath, configName)
	if err != nil {
		return err
	}
	// How many of this tool's entries the file held before the strip, so that
	// "we removed them all" can be told from "there were none". The two produce
	// identical bytes and cannot be told apart from the result alone.
	had := countOwned(a.Name(), settings)
	if err := a.StripHooks(settings); err != nil {
		return err
	}
	out, err := marshalSettings(settings)
	if err != nil {
		return err
	}

	if a.NeedsSkillsSymlink() && !skills.exists {
		if err := dir.Symlink(filepath.Join("..", ".agents", "skills"), "skills"); err != nil {
			return err
		}
		skills, err = preflightSkills(dir, dirPath)
		if err != nil {
			return err
		}
	}

	validate := func() error {
		if a.NeedsSkillsSymlink() {
			return validateSkills(dir, dirPath, skills)
		}
		return nil
	}
	// What to do with the result, and the distinction that decides it.
	//
	// "The file became empty because we deleted our entries" and "the file held
	// none of ours to begin with" produce identical bytes, so they cannot be
	// told apart from the result. Removing on the bytes alone deletes a
	// placeholder someone else wrote: measured, a config of `{"hooks":{"Stop":[]}}`
	// holds no entry of this tool's -- an empty list is not an entry -- yet it
	// stripped to `{}` and the whole file was removed. So the question asked here
	// is the only one that separates the two: did this run delete anything?
	//
	// The four outcomes: nothing removed and nothing left to write, so leave the
	// file exactly as it is (absent stays absent, a keyless file stays keyless);
	// entries removed and nothing left, so remove the file -- it existed to carry
	// them; entries removed and something left, so write the remainder back with
	// everything foreign preserved; nothing removed but the file has content of
	// its own, which is the ordinary no-op. The last two both publish.
	if isEmptySettings(out) {
		if had == 0 {
			return nil
		}
		return removeIfUnchanged(dir, dirPath, configName, snapshot, validate)
	}
	return atomicWriteHooks(dir, dirPath, configName, out, snapshot, validate)
}

// removeIfUnchanged deletes a config only while it is still the exact file this
// run read, and only when the skills invariant still holds.
//
// The removal path needs the same two checks the publish path performs, and for
// the same reasons. Without the identity check, a writer that replaces the
// config between the read and the removal loses its file -- the case
// atomicWriteHooks' own comment says it exists to prevent, and which the
// filesystem-safety suite reproduces by substituting a foreign config at the
// publish boundary. Without the skills check, a removal can leave the harness
// skills link in a state this run never validated.
func removeIfUnchanged(dir *os.Root, dirPath, name string, snapshot configSnapshot, validateSkills func() error) error {
	// The same seam the publish path crosses, and for the same reason: this is a
	// mutation of a file the caller does not own, so the identity check has to
	// happen after any racing writer has had its chance. Without this, the
	// removal path verified a file that a concurrent writer had already
	// replaced, and deleted the replacement.
	beforeWirePublish()
	current, err := dir.Lstat(name)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if !snapshot.exists {
		return fmt.Errorf("%s appeared while wiring: refusing to remove it", filepath.Join(dirPath, name))
	}
	if !isSingleLinkRegular(current) || !os.SameFile(snapshot.info, current) ||
		current.Mode() != snapshot.info.Mode() || current.Size() != snapshot.info.Size() ||
		!current.ModTime().Equal(snapshot.info.ModTime()) {
		return fmt.Errorf("%s changed while wiring: refusing to remove it", filepath.Join(dirPath, name))
	}
	if err := validateSkills(); err != nil {
		return err
	}
	if err := dir.Remove(name); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// mustMarshal serializes settings for a question that only needs the answer. An
// unserializable map is caught by the real marshal on the publish path, and
// this call must not become a second error path for it.
func mustMarshal(settings map[string]any) []byte {
	out, err := marshalSettings(settings)
	if err != nil {
		return []byte("{}")
	}
	return out
}

// isEmptySettings reports whether a marshalled config holds nothing at all.
func isEmptySettings(out []byte) bool {
	return strings.TrimSpace(string(out)) == "{}"
}

// countOwned reports how many hook commands in a config this tool owns, in any
// of the shapes it has written.
//
// It exists so the removal rule can ask the one question the stripped bytes
// cannot answer: whether an empty result means "we removed them all" or "there
// were none of ours here". It walks every key rather than a declared event list
// for the same reason the strip does -- an entry under an event this binary no
// longer knows is exactly the kind that has to be found.
//
// It is the same predicate `stripOurs` deletes by, which is the property that
// was broken once and is worth keeping: a report or a decision that is wider
// than the repair prints a remedy that cannot work.
func countOwned(harnessName string, settings map[string]any) int {
	var group map[string]any
	if harnessName == "antigravity" {
		group, _ = settings["agents"].(map[string]any)
	} else {
		group, _ = settings["hooks"].(map[string]any)
	}
	count := 0
	for _, rawList := range group {
		list, ok := rawList.([]any)
		if !ok {
			continue
		}
		for _, rawEntry := range list {
			entry, ok := rawEntry.(map[string]any)
			if !ok {
				continue
			}
			// A command directly in the list (Antigravity's shape).
			if cmd, ok := entry["command"].(string); ok {
				if IsOwnedHookCommand(cmd) {
					count++
				}
				continue
			}
			// A group wrapping a hooks list (Claude Code's and Codex's shape).
			inner, _ := entry["hooks"].([]any)
			for _, rawHook := range inner {
				hook, _ := rawHook.(map[string]any)
				if cmd, ok := hook["command"].(string); ok && IsOwnedHookCommand(cmd) {
					count++
				}
			}
		}
	}
	return count
}

// stripOurs removes previously generated entries, at the level of individual
// hooks rather than whole groups, so a group that mixes a foreign hook with
// ours keeps the foreign one.
func stripOurs(groups []any) []any {
	var kept []any
	for _, g := range groups {
		gm, ok := g.(map[string]any)
		if !ok {
			kept = append(kept, g)
			continue
		}
		rawInner, present := gm["hooks"]
		inner, ok := rawInner.([]any)
		if !present || !ok {
			// An unknown foreign shape is not ours to normalize or discard.
			kept = append(kept, g)
			continue
		}
		var innerKept []any
		for _, h := range inner {
			hm, _ := h.(map[string]any)
			if cmd, _ := hm["command"].(string); IsOwnedHookCommand(cmd) {
				continue
			}
			innerKept = append(innerKept, h)
		}
		if len(innerKept) == 0 {
			continue
		}
		gm["hooks"] = innerKept
		kept = append(kept, gm)
	}
	return kept
}
