package guard

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"runtime"
	"sort"
	"strings"
	"testing"
)

const memoryEntry = "---\nname: a\ndescription: A\nmetadata:\n  type: project\n---\n\nbody\n"

const memoryIndex = "# Memory index\n\n" +
	"GENERATED by `agents index`. Do not hand-edit — the pre-commit guard\n" +
	"regenerates this file and blocks the commit if it differs.\n\n" +
	"## project\n\n" +
	"- [a](a.md) — A\n"

const handoffEntry = "---\nlane: lane-a\nsession: s1\nstatus: reviewed\nwhen: 2026-08-10T09:00:00Z\n---\n\nbody\n"

const handoffIndex = "# Handoff index\n\n" +
	"GENERATED by `agents index`. Do not hand-edit — the pre-commit guard\n" +
	"regenerates this file and blocks the commit if it differs.\n\n" +
	"`reviewed` was written deliberately. `draft` was written automatically at\n" +
	"session end and has not been checked by anyone. Weigh them differently.\n\n" +
	"## lane-a\n\n" +
	"| when | status | session | file |\n" +
	"|---|---|---|---|\n" +
	"| 2026-08-10 09:00 | reviewed | s1 | [2026-08-10T09-00-00Z-s1.md](lane-a/2026-08-10T09-00-00Z-s1.md) |\n"

func newGuardRepo(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	for _, args := range [][]string{
		{"init", "-b", "main"},
		{"config", "user.email", "t@example.com"},
		{"config", "user.name", "T"},
		{"config", "commit.gpgsign", "false"},
	} {
		gitCommand(t, dir, nil, args...)
	}
	return dir
}

func gitCommand(t *testing.T, dir string, stdin []byte, args ...string) []byte {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Stdin = bytes.NewReader(stdin)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, out)
	}
	return out
}

func writeRepoFile(t *testing.T, root, rel, content string, mode fs.FileMode) {
	t.Helper()
	p := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(content), mode); err != nil {
		t.Fatal(err)
	}
}

func stageFiles(t *testing.T, root string) { gitCommand(t, root, nil, "add", "-A") }

func commitFiles(t *testing.T, root string) {
	t.Helper()
	gitCommand(t, root, nil, "-c", "core.hooksPath=/dev/null", "commit", "-m", "baseline")
}

func withShippedConfig(t *testing.T) {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("cannot locate guard test source")
	}
	config := filepath.Clean(filepath.Join(filepath.Dir(file), "../../../git/gitleaks.toml"))
	old := gitleaksConfigPath
	gitleaksConfigPath = func() (string, error) { return config, nil }
	t.Cleanup(func() { gitleaksConfigPath = old })
}

func fakeScanner(t *testing.T, scriptBody string) {
	t.Helper()
	dir := t.TempDir()
	script := "#!/bin/sh\nwhile IFS= read -r line; do :; done\n" + scriptBody + "\n"
	path := filepath.Join(dir, "gitleaks")
	if err := os.WriteFile(path, []byte(script), 0o755); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", dir+string(os.PathListSeparator)+os.Getenv("PATH"))
}

func fakeCleanScanner(t *testing.T) { fakeScanner(t, "exit 0") }

func withoutScanner(t *testing.T) {
	t.Helper()
	dir := t.TempDir()
	gitPath, err := exec.LookPath("git")
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink(gitPath, filepath.Join(dir, "git")); err != nil {
		t.Fatal(err)
	}
	t.Setenv("PATH", dir)
}

func blockingRule(findings []Finding, rule string) bool {
	for _, f := range findings {
		if f.Blocking && f.Rule == rule {
			return true
		}
	}
	return false
}

func ruleFindings(findings []Finding, rule string) []Finding {
	var out []Finding
	for _, f := range findings {
		if f.Rule == rule {
			out = append(out, f)
		}
	}
	return out
}

// Kills reading the working tree instead of `:<path>` in either direction.
func TestSecretScanConsumesTheStagedBlob(t *testing.T) {
	if _, err := exec.LookPath("gitleaks"); err != nil {
		t.Skip("gitleaks is not installed")
	}
	withShippedConfig(t)
	secret := "ghp_" + strings.Repeat("0123456789", 3) + "012345"

	t.Run("staged secret and clean worktree blocks", func(t *testing.T) {
		root := newGuardRepo(t)
		writeRepoFile(t, root, ".agents/note.md", secret+"\n", 0o644)
		stageFiles(t, root)
		writeRepoFile(t, root, ".agents/note.md", "clean working copy\n", 0o644)

		findings, err := Staged(root)
		if err != nil {
			t.Fatalf("Staged: %v", err)
		}
		if !blockingRule(findings, "github-pat") {
			t.Fatal("staged GitHub token was not blocked")
		}
		for _, f := range findings {
			if strings.Contains(f.Detail, secret) {
				t.Fatal("a finding disclosed the matched value")
			}
		}
	})

	t.Run("staged clean and secret worktree stays clean", func(t *testing.T) {
		root := newGuardRepo(t)
		writeRepoFile(t, root, ".agents/note.md", "clean staged copy\n", 0o644)
		stageFiles(t, root)
		writeRepoFile(t, root, ".agents/note.md", secret+"\n", 0o644)

		findings, err := Staged(root)
		if err != nil {
			t.Fatalf("Staged: %v", err)
		}
		if len(findings) != 0 {
			t.Fatalf("unstaged content affected the staged guard: %v", findings)
		}
	})
}

// Git exports these variables while running hooks. Inheriting them makes
// cmd.Dir cosmetic: the guard can inspect a different repository's index.
func TestStagedIgnoresInheritedGitRepositorySelectors(t *testing.T) {
	if _, err := exec.LookPath("gitleaks"); err != nil {
		t.Skip("gitleaks is not installed")
	}
	withShippedConfig(t)
	target := newGuardRepo(t)
	secret := "ghp_" + strings.Repeat("0123456789", 3) + "012345"
	writeRepoFile(t, target, ".agents/note.md", secret+"\n", 0o644)
	stageFiles(t, target)

	decoy := newGuardRepo(t)
	writeRepoFile(t, decoy, "main.go", "package main\n", 0o644)
	stageFiles(t, decoy)
	t.Setenv("GIT_DIR", filepath.Join(decoy, ".git"))
	t.Setenv("GIT_WORK_TREE", decoy)
	t.Setenv("GIT_INDEX_FILE", filepath.Join(decoy, ".git", "index"))

	findings, err := Staged(target)
	if err != nil {
		t.Fatalf("Staged: %v", err)
	}
	if !blockingRule(findings, "github-pat") {
		t.Fatal("inherited Git selectors redirected the guard away from its target repository")
	}
}

// Kills omitting the shipped domain extension or allowing a repository config
// to replace the trusted dotfiles config.
func TestShippedScannerConfigExtendsDefaultsAndIgnoresRepoConfig(t *testing.T) {
	if _, err := exec.LookPath("gitleaks"); err != nil {
		t.Skip("gitleaks is not installed")
	}
	withShippedConfig(t)
	cases := []struct {
		name string
		blob string
		rule string
	}{
		{"default github rule", "ghp_" + strings.Repeat("0123456789", 3) + "012345\n", "github-pat"},
		{"agent task extension", "gAAAAAB" + strings.Repeat("mZ", 18) + "\n", "encrypted-task-blob"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			root := newGuardRepo(t)
			// A repository-owned config that disables rules must have no effect.
			writeRepoFile(t, root, ".gitleaks.toml", "[allowlist]\ndescription = \"disable\"\npaths = ['''.*''']\n", 0o644)
			writeRepoFile(t, root, ".agents/note.md", tc.blob, 0o644)
			stageFiles(t, root)
			findings, err := Staged(root)
			if err != nil {
				t.Fatalf("Staged: %v", err)
			}
			if !blockingRule(findings, tc.rule) {
				t.Fatalf("configured scanner did not report rule %q", tc.rule)
			}
		})
	}
}

// Kills a scanner result mapper that prints the whole report, Match, Secret,
// stderr, or a repository-controlled rule id.
func TestScannerMappingWhitelistsSafeFields(t *testing.T) {
	withShippedConfig(t)
	root := newGuardRepo(t)
	writeRepoFile(t, root, ".agents/note.md", "ordinary text\n", 0o644)
	stageFiles(t, root)

	t.Run("only rule and line survive", func(t *testing.T) {
		fakeScanner(t, `printf '%s' '[{"RuleID":"safe-rule","StartLine":7,"Secret":"DO-NOT-PRINT","Match":"DO-NOT-PRINT","Entropy":9.9}]'; exit 1`)
		findings, err := Staged(root)
		if err != nil {
			t.Fatalf("Staged: %v", err)
		}
		got := ruleFindings(findings, "safe-rule")
		if len(got) != 1 || got[0].Line != 7 || got[0].Detail != "gitleaks detected a secret in staged content" {
			t.Fatalf("unsafe or incomplete scanner mapping: %v", got)
		}
		if strings.Contains(fmt.Sprint(got), "DO-NOT-PRINT") {
			t.Fatal("scanner payload leaked into findings")
		}
	})

	t.Run("control characters in whitelisted fields fail the scan", func(t *testing.T) {
		fakeScanner(t, `printf '%s' '[{"RuleID":"FORGED\nBLOCK","StartLine":1}]'; exit 1`)
		if _, err := Staged(root); err == nil || strings.Contains(err.Error(), "FORGED\nBLOCK") {
			t.Fatalf("unsafe scanner field was not rejected safely: %v", err)
		}
	})
}

// Kills treating exit 1 as an execution error, accepting non-1 failures, or
// waving malformed result JSON through.
func TestScannerExitClassesFailClosed(t *testing.T) {
	withShippedConfig(t)
	root := newGuardRepo(t)
	writeRepoFile(t, root, ".agents/note.md", "ordinary text\n", 0o644)
	stageFiles(t, root)

	cases := []struct {
		name        string
		script      string
		wantErr     bool
		wantFinding bool
	}{
		{"clean exit zero", "exit 0", false, false},
		{"finding exit one", `printf '%s' '[{"RuleID":"test-rule","StartLine":2}]'; exit 1`, false, true},
		{"scanner failure", `printf '%s' 'SENSITIVE-STDERR' >&2; exit 7`, true, false},
		{"malformed finding json", `printf '%s' '{'; exit 1`, true, false},
		{"empty finding report", "exit 1", true, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			fakeScanner(t, tc.script)
			findings, err := Staged(root)
			if (err != nil) != tc.wantErr {
				t.Fatalf("error = %v, wantErr %v", err, tc.wantErr)
			}
			if err != nil && strings.Contains(err.Error(), "SENSITIVE-STDERR") {
				t.Fatal("scanner stderr leaked into the error")
			}
			if blockingRule(findings, "test-rule") != tc.wantFinding {
				t.Fatalf("finding presence = %v, want %v", blockingRule(findings, "test-rule"), tc.wantFinding)
			}
		})
	}
}

// Kills dropping the trusted config or redaction arguments while leaving the
// JSON mapper intact enough for the other subprocess tests to pass.
func TestScannerInvocationCarriesItsSecurityArguments(t *testing.T) {
	withShippedConfig(t)
	root := newGuardRepo(t)
	writeRepoFile(t, root, ".agents/note.md", "ordinary text\n", 0o644)
	stageFiles(t, root)
	fakeScanner(t, `
redact=0
config=0
format=0
report=0
while [ "$#" -gt 0 ]; do
  case "$1" in
    --redact) redact=1 ;;
    --config)
      shift
      case "$1" in /*/git/gitleaks.toml) config=1 ;; esac
      ;;
    --report-format)
      shift
      [ "$1" = json ] && format=1
      ;;
    --report-path)
      shift
      [ "$1" = - ] && report=1
      ;;
  esac
  shift
done
[ "$redact$config$format$report" = 1111 ] || exit 8
exit 0`)
	findings, err := Staged(root)
	if err != nil || len(findings) != 0 {
		t.Fatalf("scanner security arguments were incomplete: findings=%v err=%v", findings, err)
	}
}

func TestMissingScannerAndConfigAreBoundedFailures(t *testing.T) {
	withShippedConfig(t)

	t.Run("no staged agent blob needs no scanner", func(t *testing.T) {
		root := newGuardRepo(t)
		writeRepoFile(t, root, "src/main.go", "package main\n", 0o644)
		stageFiles(t, root)
		withoutScanner(t)
		findings, err := Staged(root)
		if err != nil || len(findings) != 0 {
			t.Fatalf("out-of-scope commit consulted scanner: findings=%v err=%v", findings, err)
		}
	})

	t.Run("an agent blob requires scanner", func(t *testing.T) {
		root := newGuardRepo(t)
		writeRepoFile(t, root, ".agents/note.md", "clean\n", 0o644)
		stageFiles(t, root)
		withoutScanner(t)
		_, err := Staged(root)
		if err == nil || !strings.Contains(err.Error(), "brew install gitleaks") {
			t.Fatalf("missing scanner did not fail with remediation: %v", err)
		}
	})

	t.Run("an agent blob requires trusted config", func(t *testing.T) {
		root := newGuardRepo(t)
		writeRepoFile(t, root, ".agents/note.md", "clean\n", 0o644)
		stageFiles(t, root)
		fakeCleanScanner(t)
		old := gitleaksConfigPath
		gitleaksConfigPath = func() (string, error) { return filepath.Join(t.TempDir(), "missing.toml"), nil }
		t.Cleanup(func() { gitleaksConfigPath = old })
		before := snapshotRepo(t, root)
		if _, err := Staged(root); err == nil {
			t.Fatal("missing dotfiles config was treated as a clean scan")
		}
		if after := snapshotRepo(t, root); !reflect.DeepEqual(before, after) {
			t.Fatal("missing-config failure mutated the repository")
		}
	})

	t.Run("an unreadable config path is not delegated as clean", func(t *testing.T) {
		root := newGuardRepo(t)
		writeRepoFile(t, root, ".agents/note.md", "clean\n", 0o644)
		stageFiles(t, root)
		fakeCleanScanner(t)
		old := gitleaksConfigPath
		directory := t.TempDir()
		gitleaksConfigPath = func() (string, error) { return directory, nil }
		t.Cleanup(func() { gitleaksConfigPath = old })
		if _, err := Staged(root); err == nil {
			t.Fatal("non-file dotfiles config was treated as a clean scan")
		}
	})
}

// Kills a generated-file comparison based on the unstaged working tree.
func TestGeneratedIndexesAreRenderedFromTheIndexSnapshot(t *testing.T) {
	withShippedConfig(t)
	fakeCleanScanner(t)

	t.Run("memory", func(t *testing.T) {
		root := newGuardRepo(t)
		writeRepoFile(t, root, ".agents/memory/a.md", memoryEntry, 0o644)
		writeRepoFile(t, root, ".agents/memory/INDEX.md", memoryIndex, 0o644)
		stageFiles(t, root)
		writeRepoFile(t, root, ".agents/memory/a.md", "broken unstaged content\n", 0o600)

		findings, err := Staged(root)
		if err != nil {
			t.Fatalf("Staged: %v", err)
		}
		if blockingRule(findings, "generated-file") {
			t.Fatal("unstaged memory content changed the expected generated bytes")
		}
	})

	t.Run("handoff", func(t *testing.T) {
		root := newGuardRepo(t)
		writeRepoFile(t, root, ".agents/reports/handoff/lane-a/2026-08-10T09-00-00Z-s1.md", handoffEntry, 0o644)
		writeRepoFile(t, root, ".agents/reports/handoff/INDEX.md", handoffIndex, 0o644)
		stageFiles(t, root)
		writeRepoFile(t, root, ".agents/reports/handoff/lane-a/2026-08-10T09-00-00Z-s1.md", "broken unstaged content\n", 0o600)

		findings, err := Staged(root)
		if err != nil {
			t.Fatalf("Staged: %v", err)
		}
		if blockingRule(findings, "generated-file") {
			t.Fatal("unstaged handoff content changed the expected generated bytes")
		}
	})
}

// memory.WriteIndex only owns INDEX.md at the memory root. A nested file with
// that basename is ignored by memory.List and cannot collide with the output.
func TestNestedIndexNameDoesNotCreateAFalseGeneratedFailure(t *testing.T) {
	withShippedConfig(t)
	fakeCleanScanner(t)
	root := newGuardRepo(t)
	writeRepoFile(t, root, ".agents/memory/a.md", memoryEntry, 0o644)
	writeRepoFile(t, root, ".agents/memory/INDEX.md", memoryIndex, 0o644)
	writeRepoFile(t, root, ".agents/memory/archive/index.md", "archived prose\n", 0o644)
	stageFiles(t, root)

	findings, err := Staged(root)
	if err != nil {
		t.Fatalf("nested memory file was treated as an index collision: %v", err)
	}
	if blockingRule(findings, "generated-file") {
		t.Fatal("a nested index basename changed the root memory index")
	}
}

func TestGeneratedIndexMissingMismatchAndMalformedSource(t *testing.T) {
	withShippedConfig(t)
	fakeCleanScanner(t)
	cases := []struct {
		name      string
		files     map[string]string
		wantError bool
	}{
		{"missing", map[string]string{".agents/memory/a.md": memoryEntry}, false},
		{"mismatch", map[string]string{".agents/memory/a.md": memoryEntry, ".agents/memory/INDEX.md": "hand edited\n"}, false},
		{"malformed source", map[string]string{".agents/memory/a.md": "no frontmatter\n", ".agents/memory/INDEX.md": memoryIndex}, true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			root := newGuardRepo(t)
			for rel, content := range tc.files {
				writeRepoFile(t, root, rel, content, 0o644)
			}
			stageFiles(t, root)
			findings, err := Staged(root)
			if (err != nil) != tc.wantError {
				t.Fatalf("error = %v, wantError %v", err, tc.wantError)
			}
			if !tc.wantError && !blockingRule(findings, "generated-file") {
				t.Fatal("missing or mismatched generated index did not block")
			}
		})
	}
}

func TestDeletingAGeneratedIndexBlocks(t *testing.T) {
	withShippedConfig(t)
	fakeCleanScanner(t)
	root := newGuardRepo(t)
	writeRepoFile(t, root, ".agents/memory/a.md", memoryEntry, 0o644)
	writeRepoFile(t, root, ".agents/memory/INDEX.md", memoryIndex, 0o644)
	stageFiles(t, root)
	commitFiles(t, root)
	gitCommand(t, root, nil, "rm", ".agents/memory/INDEX.md")

	findings, err := Staged(root)
	if err != nil {
		t.Fatalf("Staged: %v", err)
	}
	if !blockingRule(findings, "generated-file") {
		t.Fatal("deleting a generated index was not blocked")
	}
}

func TestMixedCommitIsAdvisory(t *testing.T) {
	withShippedConfig(t)
	fakeCleanScanner(t)
	root := newGuardRepo(t)
	writeRepoFile(t, root, ".agents/note.md", "note\n", 0o644)
	writeRepoFile(t, root, "src/main.go", "package main\n", 0o644)
	stageFiles(t, root)
	findings, err := Staged(root)
	if err != nil {
		t.Fatalf("Staged: %v", err)
	}
	got := ruleFindings(findings, "mixed-commit")
	if len(got) != 1 || got[0].Blocking {
		t.Fatalf("mixed commit finding is not advisory: %v", got)
	}
}

func TestStagedPathLifecycleUsesNULTerminatedGitNames(t *testing.T) {
	withShippedConfig(t)
	fakeScanner(t, `printf '%s' '[{"RuleID":"test-rule","StartLine":3}]'; exit 1`)
	cases := []struct {
		name        string
		setup       func(*testing.T, string) string
		wantFinding bool
	}{
		{"add with spaces and glob characters", func(t *testing.T, root string) string {
			p := ".agents/notes [*]?.md"
			writeRepoFile(t, root, p, "new\n", 0o644)
			stageFiles(t, root)
			return p
		}, true},
		{"modify", func(t *testing.T, root string) string {
			p := ".agents/note.md"
			writeRepoFile(t, root, p, "old\n", 0o644)
			stageFiles(t, root)
			commitFiles(t, root)
			writeRepoFile(t, root, p, "new\n", 0o644)
			stageFiles(t, root)
			return p
		}, true},
		{"rename", func(t *testing.T, root string) string {
			old, p := ".agents/note.md", ".agents/renamed [*]?.md"
			writeRepoFile(t, root, old, "old\n", 0o644)
			stageFiles(t, root)
			commitFiles(t, root)
			gitCommand(t, root, nil, "mv", old, p)
			return p
		}, true},
		{"delete", func(t *testing.T, root string) string {
			p := ".agents/note.md"
			writeRepoFile(t, root, p, "old\n", 0o644)
			stageFiles(t, root)
			commitFiles(t, root)
			gitCommand(t, root, nil, "rm", p)
			return p
		}, false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			root := newGuardRepo(t)
			path := tc.setup(t, root)
			findings, err := Staged(root)
			if err != nil {
				t.Fatalf("Staged: %v", err)
			}
			got := ruleFindings(findings, "test-rule")
			if (len(got) > 0) != tc.wantFinding {
				t.Fatalf("finding presence = %v, want %v", len(got) > 0, tc.wantFinding)
			}
			if tc.wantFinding && (len(got) != 1 || got[0].Path != path) {
				t.Fatalf("scanner finding path = %v, want %q", got, path)
			}
		})
	}
}

func TestConflictedIndexFailsClosed(t *testing.T) {
	withShippedConfig(t)
	fakeCleanScanner(t)
	root := newGuardRepo(t)
	path := ".agents/note.md"
	writeRepoFile(t, root, path, "base\n", 0o644)
	stageFiles(t, root)
	commitFiles(t, root)

	base := strings.TrimSpace(string(gitCommand(t, root, []byte("base\n"), "hash-object", "-w", "--stdin")))
	ours := strings.TrimSpace(string(gitCommand(t, root, []byte("ours\n"), "hash-object", "-w", "--stdin")))
	theirs := strings.TrimSpace(string(gitCommand(t, root, []byte("theirs\n"), "hash-object", "-w", "--stdin")))
	gitCommand(t, root, []byte(fmt.Sprintf("0 0000000000000000000000000000000000000000\t%s\n100644 %s 1\t%s\n100644 %s 2\t%s\n100644 %s 3\t%s\n", path, base, path, ours, path, theirs, path)), "update-index", "--index-info")

	if _, err := Staged(root); err == nil {
		t.Fatal("a conflicted in-scope index entry was waved through")
	}
}

func TestControlCharacterPathIsBlockedWithoutTerminalInjection(t *testing.T) {
	withShippedConfig(t)
	fakeCleanScanner(t)
	root := newGuardRepo(t)
	raw := ".agents/FORGED\nBLOCK.md"
	writeRepoFile(t, root, raw, "clean\n", 0o644)
	stageFiles(t, root)
	findings, err := Staged(root)
	if err != nil {
		t.Fatalf("Staged: %v", err)
	}
	if !blockingRule(findings, "unsafe-path") {
		t.Fatal("control-character path was not blocked")
	}
	for _, f := range findings {
		if strings.Contains(f.Path, "\n") || strings.Contains(f.Detail, "FORGED\nBLOCK") {
			t.Fatalf("raw control path escaped into a finding: %q", fmt.Sprint(f))
		}
	}
}

type worktreeFile struct {
	Mode fs.FileMode
	Data string
}

type repoSnapshot struct {
	Worktree map[string]worktreeFile
	Index    string
}

// snapshotRepo is intentionally independent of production guard helpers. It
// observes every worktree entry outside .git and Git's mode/stage/blob table.
func snapshotRepo(t *testing.T, root string) repoSnapshot {
	t.Helper()
	worktree := map[string]worktreeFile{}
	err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, p)
		if err != nil {
			return err
		}
		if rel == ".git" {
			return filepath.SkipDir
		}
		if rel == "." {
			return nil
		}
		info, err := os.Lstat(p)
		if err != nil {
			return err
		}
		item := worktreeFile{Mode: info.Mode()}
		switch {
		case info.Mode()&os.ModeSymlink != 0:
			item.Data, err = os.Readlink(p)
		case info.Mode().IsRegular():
			var b []byte
			b, err = os.ReadFile(p)
			item.Data = string(b)
		}
		if err != nil {
			return err
		}
		worktree[filepath.ToSlash(rel)] = item
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	index := string(gitCommand(t, root, nil, "ls-files", "--stage", "-z"))
	return repoSnapshot{Worktree: worktree, Index: index}
}

func TestEveryStagedOutcomeIsObservational(t *testing.T) {
	withShippedConfig(t)
	cases := []struct {
		name    string
		files   map[string]string
		scanner string
		missing bool
	}{
		{"clean", map[string]string{"src/main.go": "package main\n"}, "exit 0", false},
		{"advisory", map[string]string{".agents/note.md": "note\n", "src/main.go": "package main\n"}, "exit 0", false},
		{"finding", map[string]string{".agents/note.md": "note\n"}, `printf '%s' '[{"RuleID":"test-rule","StartLine":1}]'; exit 1`, false},
		{"scanner missing", map[string]string{".agents/note.md": "note\n"}, "", true},
		{"scanner error", map[string]string{".agents/note.md": "note\n"}, "exit 7", false},
		{"malformed json", map[string]string{".agents/note.md": "note\n"}, `printf '%s' '{'; exit 1`, false},
		{"malformed tracked entry", map[string]string{".agents/memory/a.md": "broken\n", ".agents/memory/INDEX.md": memoryIndex}, "exit 0", false},
		{"missing generated index", map[string]string{".agents/memory/a.md": memoryEntry}, "exit 0", false},
		{"generated mismatch", map[string]string{".agents/memory/a.md": memoryEntry, ".agents/memory/INDEX.md": "wrong\n"}, "exit 0", false},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			root := newGuardRepo(t)
			for rel, content := range tc.files {
				writeRepoFile(t, root, rel, content, 0o640)
			}
			stageFiles(t, root)
			if tc.missing {
				withoutScanner(t)
			} else {
				fakeScanner(t, tc.scanner)
			}
			before := snapshotRepo(t, root)
			_, _ = Staged(root)
			after := snapshotRepo(t, root)
			if !reflect.DeepEqual(before, after) {
				t.Fatalf("Staged mutated repository state\nbefore: %#v\nafter:  %#v", before, after)
			}
		})
	}
}

func TestStagedFindingsAreDeterministicallyOrdered(t *testing.T) {
	withShippedConfig(t)
	fakeScanner(t, `printf '%s' '[{"RuleID":"z-rule","StartLine":3},{"RuleID":"a-rule","StartLine":2}]'; exit 1`)
	root := newGuardRepo(t)
	for _, rel := range []string{".agents/z.md", ".agents/a.md"} {
		writeRepoFile(t, root, rel, "note\n", 0o644)
	}
	stageFiles(t, root)
	findings, err := Staged(root)
	if err != nil {
		t.Fatal(err)
	}
	got := append([]Finding(nil), findings...)
	if len(findings) != 4 {
		t.Fatalf("two scanner findings for each of two staged blobs = 4, got %d", len(findings))
	}
	sort.Slice(got, func(i, j int) bool {
		if got[i].Path != got[j].Path {
			return got[i].Path < got[j].Path
		}
		if got[i].Line != got[j].Line {
			return got[i].Line < got[j].Line
		}
		return got[i].Rule < got[j].Rule
	})
	if fmt.Sprint(got) != fmt.Sprint(findings) {
		t.Fatalf("findings are not stable: %v", findings)
	}
}
