#!/usr/bin/env zsh

function pathmunge () {
    if [[ $(uname) == "Darwin" ]]; then
        grep="/usr/bin/grep"
    else
        grep="/bin/grep"
    fi
    if ! echo "$PATH" | $grep -Eq "(^|:)$1($|:)" ; then
        if [ "$2" = "after" ] ; then
            PATH="$PATH:$1"
        else
            PATH="$1:$PATH"
        fi
    fi
}

for f in $(ls "$HOME"/dotfiles/zsh/*.env); do
    source $f
done

export PATH_SAVE=$PATH # to unfxxk the macOS's `path_helper`

